import enumeradores.AlmacenAlimentos;
import modelos.DukeMascota;
import persistencia.persistenceCollections.MascotaPersistenceUseList;

public class Main {

  public static void main(String[] args) {
    MascotaPersistenceUseList persistence = new MascotaPersistenceUseList();

    DukeMascota duke = new DukeMascota("Duke-Merlina", "Semper");
    DukeMascota duke2 = new DukeMascota("Duke-Cordobes", "Semper");
    DukeMascota duke3 = new DukeMascota("Duke-Porteño", "Semper");
    DukeMascota duke4 = new DukeMascota("Duke-Litoral", "Semper");
    persistence.guardar(duke);
    persistence.guardar(duke2);
    persistence.guardar(duke3);
    persistence.guardar(duke4);

//    System.out.println("antes de comer " + duke.getNivelEnergia());
//    duke.comer(AlmacenAlimentos.ASADO);
//    System.out.println("despues de comer " + duke.getNivelEnergia());
//
//    duke.jugar(EntretenimientosEnum.POKER);
//    duke.jugar(EntretenimientosEnum.PASEAR);
//    duke.jugar(EntretenimientosEnum.PASEAR);
//    duke.jugar(EntretenimientosEnum.PERINOLA);
//    duke.jugar(EntretenimientosEnum.BAILAR);
//    duke.jugar(EntretenimientosEnum.BAILAR);
//    System.out.println("antes de dormir " + duke.getNivelEnergia());
//    duke.dormir(LocalTime.of(0,25));
//    System.out.println("despues de dormir " + duke.getNivelEnergia());

    System.out.println("energia :" + duke.getNivelEnergia());
    duke.comer(AlmacenAlimentos.ASADO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.ASADO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());

    System.out.println("");
    System.out.println("duke come");
    duke.comer(AlmacenAlimentos.ASADO);
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());

    System.out.println("");
    duke.comer(AlmacenAlimentos.ASADO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());

    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    System.out.println("duke va al baño");
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    System.out.println("");
    duke.comer(AlmacenAlimentos.PORORO);
    System.out.println("duke come");
    System.out.println("comidas ingeridas " + duke.getComidasIngeridas());
    System.out.println("energia :" + duke.getNivelEnergia());
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    duke.irAlBaño();
    System.out.println(duke.getComidasIngeridas());
  }
}
